### ISSUE TITLE
FEAT: Add Roski sites

### ISSUE THREAD

**Issue by troutacular** [uscwebservices/usc-wordpress-pantheon-upstream-gateway-sso-xml#505]
Add the following for SSO

dev-usc-dp-roski.pantheonsite.io
test-usc-dp-roski.pantheonsite.io
live-usc-dp-roski.pantheonsite.io
roski.usc.edu

**Comment by calvin-usc** [comment]
https://usc-its-jira-cloud.atlassian.net/browse/DEV-4988
