### ISSUE TITLE
Add Graduate Admissions for DP CCL

### ISSUE THREAD

**Issue by troutacular** [uscwebservices/usc-wordpress-pantheon-upstream-gateway-sso-xml#592]
Add domains using WP root login location:

- gradadm.usc.edu
- dev-usc-graduate-admissions.pantheonsite.io
- test-usc-graduate-admissions.pantheonsite.io
- live-usc-graduate-admissions.pantheonsite.io

**Comment by calvin-usc** [comment]
tracking on https://usc-its-jira-cloud.atlassian.net/browse/DEV-5737
